### PR TITLE
Adding Nixer to serialize Ruby objects to Nix expressions

### PR DESCRIPTION
**Pull request by nyarly**

### CODE REVIEW

**Comment by zimbatm** [comment]
How did you end-up rewriting Bundix.obect2nix, is it solving a problem that you were having with the current implementation?

**Comment by nyarly** [comment]
Not for the current feature set, but the motivation behind all these changes is a more complete support for Gemfile features (groups, platforms, etc.) and as a result the object2nix code became more complex. I wanted to be able to test that the serialization worked well, which motivated extracting the code.

On the previous mega-PR, @manveru (I think?) had called out this extraction in particular, which is also part of why I'm reproducing it.

**Comment by zimbatm** [comment]
Thanks for the reminder. I wanted to understand this as it adds more complexity to the code.

I think the PR is fine but should also remove the original method and ideally have some tests for the code.

**Comment by nyarly** [comment]
Good point re removing the original method. There are some tests for the new code at test/nixer.rb

**Comment by zimbatm** [comment]
Great, thanks!

**Pull request merged**
