### PR TITLE
fetch git submodules

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
fixes #46

**Comment by alyssais** [comment]
Thanks for the PR! I was just pushing my own fix for this. I don't think this is quite right, though, because we don't want to always install submodules – that's not Bundler's behaviour either.

**Comment by alyssais** [comment]
Here's what I had: 

```diff
﻿﻿diff --git a/lib/bundix/source.rb b/lib/bundix/source.rb
index 7cea238..8bc23ca 100644
--- a/lib/bundix/source.rb
+++ b/lib/bundix/source.rb
@@ -72,10 +72,18 @@ class Bundix
       nil
     end
 
-    def nix_prefetch_git(uri, revision)
+    def nix_prefetch_git(uri, revision, submodules: false)
       home = ENV['HOME']
       ENV['HOME'] = '/homeless-shelter'
-      sh(NIX_PREFETCH_GIT, '--url', uri, '--rev', revision, '--hash', 'sha256', '--leave-dotGit')
+
+      args = []
+      args << '--url' << uri
+      args << '--rev' << revision
+      args << '--hash' << 'sha256'
+      args << '--leave-dotGit'
+      args << '--fetch-submodules' if submodules
+
+      sh(NIX_PREFETCH_GIT, *args)
     ensure
       ENV['HOME'] = home
     end
@@ -153,7 +161,8 @@ class Bundix
     def convert_git
       revision = spec.source.options.fetch('revision')
       uri = spec.source.options.fetch('uri')
-      output = fetcher.nix_prefetch_git(uri, revision)
+      submodules = spec.source.submodules
+      output = fetcher.nix_prefetch_git(uri, revision, submodules: submodules)
       # FIXME: this is a hack, we should separate $stdout/$stderr in the sh call
       hash = JSON.parse(output[/({[^}]+})\s*\z/m])['sha256']
       fail "couldn't fetch hash for #{spec.full_name}" unless hash
@@ -163,7 +172,7 @@ class Bundix
         url: uri.to_s,
         rev: revision,
         sha256: hash,
-        fetchSubmodules: false }
+        fetchSubmodules: spec.source.submodules }
     end
   end
 end
```

**Comment by alyssais** [comment]
I'm not sure what the etiquette here is since we both had fixes at about the same time, but I think mine is closer to being what we want. Would you mind if I proceeded with my attempt rather than this one?

**Comment by ghost** [comment]
I don't really care :-)

**Comment by ghost** [comment]
I will just close this and you can open a PR with the proper fix

**Pull request closed without merging**
