### PR TITLE
Handle git submodules

### LINKED ISSUE #46: git submodules are not cloned
This is at the top of my Gemfile.lock:

```
GIT
  remote: https://github.com/tmm1/http_parser.rb
  revision: 54b17ba8c7d8d20a16dfc65d1775241833219cf2
  ref: 54b17ba8c7d8d20a16dfc65d1775241833219cf2
  specs:
    http_parser.rb (0.6.1)
```

http_parser fails to build, because the git submodule in ext/ruby_http_parser/vendor/http-parser is not cloned.

```
    current directory: /nix/store/0gx1ydxnqab5crprz48bwz0vjprnmq39-ruby2.6.1-http_parser.rb-0.6.1/lib/ruby/gems/2.6.0/bundler/gems/http_parser.rb-54b17ba8c7d8/ext/ruby_http_parser
/nix/store/9h785sf1zqw26zn8rhrcqq3xcz1gw4v7-ruby-2.6.1/bin/ruby -I /nix/store/9h785sf1zqw26zn8rhrcqq3xcz1gw4v7-ruby-2.6.1/lib/ruby/2.6.0 -r ./siteconf20190322-697-aqdpkf.rb extconf.rb ''
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/nix/store/9h785sf1zqw26zn8rhrcqq3xcz1gw4v7-ruby-2.6.1/bin/$(RUBY_BASE_NAME)
extconf.rb:17:in `read': No such file or directory @ rb_sysopen - /nix/store/0gx1ydxnqab5crprz48bwz0vjprnmq39-ruby2.6.1-http_parser.rb-0.6.1/lib/ruby/gems/2.6.0/bundler/gems/http_parser.rb-54b17ba8c7d8/ext/ruby_http_parser/vendor/http-parser/http_parser.c (Errno::ENOENT)
        from extconf.rb:17:in `block (2 levels) in <main>'
        from extconf.rb:16:in `open'
        from extconf.rb:16:in `block in <main>'
        from extconf.rb:15:in `each'
        from extconf.rb:15:in `<main>'

extconf failed, exit code 1
```

### PR DESCRIPTION
**Pull request by alyssais**
Fixes https://github.com/manveru/bundix/issues/46.

cc @petabyteboy

### CODE REVIEW

**Comment by ghost** [comment]
I'm not sure how bundler does it, but it builds the http_parser gem just fine with the lockfile from https://github.com/tootsuite/mastodon/, while this does not (still the same problem as in #46).

**Comment by ghost** [comment]
Okay. This is fine for me, I will patch Gemfile.lock to add submodules: true.

**Comment by ghost** [comment]
Can we merge this? @manveru

**Comment by ghost** [comment]
I resolved the conflict in the feature/submodules branch on my fork

**Comment by manveru** [comment]
hey @petabyteboy, if you make a separate PR from your branch, I'll merge it and cut a new release.

**Comment by ghost** [comment]
> hey @petabyteboy, if you make a separate PR from your branch, I'll merge it and cut a new release.

done: #62

**Pull request closed without merging**
