### PR TITLE
Handle path sources (e.g. gemspec directives)

### PR DESCRIPTION
**Pull request by nyarly**

### CODE REVIEW

**Comment by Mic92** [comment]
I tried to use this change on this [project](https://github.com/Binaergewitter/serious-bg), but it is still produces an error:

```
$ bundix
#<Bundler::LazySpecification:0x00000000010254d0
 @__identifier=
  #<struct Bundler::LazySpecification::Identifier
   name="serious",
   version=Gem::Version.new("0.3.2"),
   source=#<Bundler::Source::Path:0x9578520 source at `serious`>,
   platform="ruby",
   dependencies=
    [Gem::Dependency.new("builder",
      Gem::Requirement.new([">= 2.1.2"]),
      :runtime),
     Gem::Dependency.new("excon",
      Gem::Requirement.new(["~> 0.49.0"]),
      :runtime),
     Gem::Dependency.new("sinatra",
      Gem::Requirement.new([">= 1.0.0"]),
      :runtime),
     Gem::Dependency.new("stupid_formatter",
      Gem::Requirement.new([">= 0.2.0"]),
      :runtime)]>,
 @dependencies=
  [Gem::Dependency.new("builder",
    Gem::Requirement.new([">= 2.1.2"]),
    :runtime),
   Gem::Dependency.new("excon", Gem::Requirement.new(["~> 0.49.0"]), :runtime),
   Gem::Dependency.new("sinatra",
    Gem::Requirement.new([">= 1.0.0"]),
    :runtime),
   Gem::Dependency.new("stupid_formatter",
    Gem::Requirement.new([">= 0.2.0"]),
    :runtime)],
 @name="serious",
 @platform="ruby",
 @source=#<Bundler::Source::Path:0x9578520 source at `serious`>,
 @specification=nil,
 @version=Gem::Version.new("0.3.2")>
Skipping serious: unkown bundler source
/nix/store/4yxq9isf3k78nkvnl9fddfsy0m4g6f8x-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/lib/bundix/source.rb:11:in `convert'
/nix/store/4yxq9isf3k78nkvnl9fddfsy0m4g6f8x-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/lib/bundix.rb:48:in `convert_spec'
/nix/store/4yxq9isf3k78nkvnl9fddfsy0m4g6f8x-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/lib/bundix.rb:38:in `block in convert'
/nix/store/4yxq9isf3k78nkvnl9fddfsy0m4g6f8x-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/lib/bundix.rb:37:in `reverse_each'
/nix/store/4yxq9isf3k78nkvnl9fddfsy0m4g6f8x-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/lib/bundix.rb:37:in `with_object'
/nix/store/4yxq9isf3k78nkvnl9fddfsy0m4g6f8x-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/lib/bundix.rb:37:in `convert'
/nix/store/4yxq9isf3k78nkvnl9fddfsy0m4g6f8x-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/bin/bundix:112:in `<top (required)>'
/nix/store/4yxq9isf3k78nkvnl9fddfsy0m4g6f8x-bundix-2.3.1/bin/.bundix-wrapped:18:in `load'
/nix/store/4yxq9isf3k78nkvnl9fddfsy0m4g6f8x-bundix-2.3.1/bin/.bundix-wrapped:18:in `<main>'
```


This is the breaking gem: 
https://github.com/Binaergewitter/serious-bg/blob/d355f2ac4410954e345decc24e737aa6165e3f93/Gemfile#L4

The resulting gemset entry looks like this:
```
  serious = {
    dependencies = ["builder" "excon" "sinatra" "stupid_formatter"];
  };
```

Creating a package also does not work that way:

```
{ pkgs ? import <nixpkgs> {} }:
with pkgs;
let
  gems = bundlerEnv {
    name = "your-package";
    inherit ruby;
    gemdir  = ./.;
  };
in stdenv.mkDerivation {
  name = "your-package";
  src = ./.;
  buildInputs = [gems ruby];
  installPhase = ''
    mkdir -p $out
    cp -r $src $out
  '';
}
```

```
$ nix-build
error: attribute 'source' missing, at /home/joerg/git/nixpkgs/pkgs/development/ruby-modules/bundled-common/functions.nix:72:14
(use '--show-trace' to show detailed location information)
```

**Comment by nyarly** [comment]
@Mic92 You're still using the packaged Bundix there - I've had to add the `bin/` directory of my checkout of bundix to my PATH in order to test this change out.

Note also that you'll need a recent checkout of nixpkgs - there was a bug in the way bunderEnv handled path sources.

**Comment by Mic92** [comment]
Indeed. My mistake. Now it works.

**Comment by nyarly** [comment]
:tada:

**Pull request merged**
